### ISSUE TITLE
Not sure if my privacy will be untouched

### ISSUE THREAD

**Issue by pablonic** [igdmapps/igdm#1269]
Hi! 
I think that maybe this isn't pretty safe, because the actual developers can see all my private fiends, messages and all that stuff, am I right?

**Comment by someone857** [comment]
No. Developers just create the app, they cannot see what happens when you login and make usage of your credentials. When you login, your credentials are securely stored on your own machine and they are used to authenticate against Instagram on your own machine to retriever your data to your own machine. None of these are visible to the developers.
