### ISSUE TITLE
[Pro Version] Link to buy license doesn't allow you to buy the license.

### ISSUE THREAD

**Issue by salazarbarrera** [igdmapps/igdm#1523]
I'm not sure if I'm missing something in the website, but after a long time using free IGdm in Manjaro Linux, I wanted to try the Pro version, but  a prompt asking for license key appears. When I click the "Buy License" link, it takes me to https://pro.igdm.me/ , but there's no link to pay anywhere in the website.

**Comment by ifedapoolarewaju** [comment]
Hi, the payment link was temporarily disabled because the IGdm Pro app was broken and needed some fixes. We didn't want to have people pay for a broken app.

A completely new version has now been released with the payment link now re-enabled.

Please visit https://pro.igdm.me/ to download the latest version
