### ISSUE TITLE
I can't buy PRO license

### ISSUE THREAD

**Issue by AngelowTP** [igdmapps/igdm#1542]
When i press "Buy pro license" nothing's happen. 

How can i buy the pro version ?

**Comment by spinalgr1990** [comment]
the developer is sleeping...

**Comment by ifedapoolarewaju** [comment]
Hi, the payment link was temporarily disabled because the IGdm Pro app was broken and needed some fixes. We didn't want to have people pay for a broken app.

A completely new version has now been released with the payment link now re-enabled.

Please visit https://pro.igdm.me/ to download the latest version
